project_id = "yupdlssiyebcunznwhjc"

[functions.migrate-excel-data]
verify_jwt = false

[functions.n8n-proxy]
verify_jwt = false

[functions.admin-update-user-email]
verify_jwt = false

[functions.send-recovery-email]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.create-super-admin]
verify_jwt = false
