// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wegavwujisdkufercayo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZ2F2d3VqaXNka3VmZXJjYXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MDI1NzgsImV4cCI6MjA3MjA3ODU3OH0.JNdyL5X0WtcmLwrRB_VqmlItVdDKaRg2ZwByG-D2ViU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});